### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by xeotrel2** [MonochromeSun/atom-together#1]
[Enter steps to reproduce:]

1. Select the treeview
2. Execute Atom Together: Stac

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-together](https://github.com/MonochromeSun/atom-together) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of null

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:854

TypeError: Cannot read property 'slice' of null
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:621:31)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:574:25)
    at /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:554:32
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:849:24)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:552:27)
    at TextBuffer.module.exports.TextBuffer.setText (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:492:25)
    at TextEditor.module.exports.TextEditor.setText (/usr/share/atom/resources/app/src/text-editor.js:1102:32)
    at ClientInputView.module.exports.ClientInputView.initialize (/packages/atom-together/lib/views/clientInput.coffee:53:65)
    at ClientInputView.initialize (/packages/atom-together/lib/views/clientInput.coffee:1:1)
    at Object.createView (/packages/atom-together/lib/init.coffee:137:19)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:121:84)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:88:27)
    at atom-pane.PaneElement.itemRemoved (/usr/share/atom/resources/app/src/pane-element.js:186:37)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:613:26)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:685:22)
    at TabBarView.module.exports.TabBarView.closeTab (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
     -4:22.6.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:04.7.0 application:open-folder (atom-pane.pane.active)
     -2:32.9.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:13.1.0 core:confirm (input.hidden-input)
     -1:19.5.0 core:backspace (input.hidden-input)
     -1:18.1.0 core:confirm (input.hidden-input)
  2x -0:43.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:35.2.0 atom-together:stac (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-together 0.3.1 
tool-bar 1.1.0 
tool-bar-basic 2.0.1 
```

**Comment by MonochromeSun** [comment]
This bug is caused for me by selecting the tree-view as a whole and not a folder/file within it.  Can you reproduce this where you have right clicked on a folder/file?
